### ISSUE TITLE
Trailing comma

### ISSUE THREAD

**Issue by sojamo** [aqiank/serialindex-arduino#1]
Last value inside an array is followed by an additional comma `cm=[160,158,159,]` but should be closing bracket.

**Comment by aqiank** [comment]
Hi Andreas, trailing comma is accepted but is not necessary.

**Comment by sojamo** [comment]
when sending from serialindex-arduino the comma is included which could trouble other implementations when parsing. For this reason, could it be removed?

**Comment by aqiank** [comment]
Okay, understood. I have removed the extra comma in the `dev` branch.

**Comment by sojamo** [comment]
nice.
